name: Process PMC XML

on:
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Python and dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.5'
    - run: |
        python -m pip install --upgrade pip
        pip install lxml requests

    - name: Download PMC .tar.gz
      run: |
        wget https://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_bulk/oa_comm/xml/oa_comm_xml.PMC000xxxxxx.baseline.2025-06-26.tar.gz -O data.tar.gz

    - name: Extract, parse, and embed XMLs
      run: |
        python scripts/process_pmc.py
      env:
        HF_TOKEN: ${{secrets.HF_TOKEN}}

    - name: Commit results
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
        git add local_embeddings/
        git commit -m "Processed PMC000xxxxxx"
        git push